[[redirects]]
  from = "/api/*"
  to = "https://api.laundrylabels.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://api.laundrylabels.app/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/upload/*"
  to = "https://api.laundrylabels.app/upload/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
